[build]
  publish = "public"
  
[[plugins]]
  package = "@netlify/plugin-onbuild"

  # 잘못된 구문: [[plugins.inputs]] -> 올바르게 수정
  [plugins.inputs]  # 여기에서 inputs는 plain object여야 합니다.
    onBuild = "node fetch-hotdeals.js"
